"""Add maintenance kanban fields

Revision ID: 7398c2fc090e
Revises: 5d08ffee0fe6
Create Date: 2026-03-19 14:58:55.564195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '7398c2fc090e'
down_revision: Union[str, None] = '5d08ffee0fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_logs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('maintenance_logs', sa.Column('priority', sa.String(length=20), nullable=False))
    op.alter_column('maintenance_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_maintenance_logs_status'), 'maintenance_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_logs_status'), table_name='maintenance_logs')
    op.alter_column('maintenance_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('maintenance_logs', 'priority')
    op.drop_column('maintenance_logs', 'status')
    # ### end Alembic commands ###
